// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo4GDVx6Dnp1rROs78KLqn9E286aC0z54',
    appId: '1:331308178402:web:7e8d81c3f2491e5fb737bb',
    messagingSenderId: '331308178402',
    projectId: 'manga-bec41',
    authDomain: 'manga-bec41.firebaseapp.com',
    storageBucket: 'manga-bec41.appspot.com',
    measurementId: 'G-LJ04JP2B5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIrSc5uTRGajZbusTR6miU8i3iNEJuUbg',
    appId: '1:331308178402:android:3667e94b9ceecca7b737bb',
    messagingSenderId: '331308178402',
    projectId: 'manga-bec41',
    storageBucket: 'manga-bec41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2TVX2ik-uqoCTyL50grg-HDcVslDH8Z4',
    appId: '1:331308178402:ios:0e1d156480f47c1db737bb',
    messagingSenderId: '331308178402',
    projectId: 'manga-bec41',
    storageBucket: 'manga-bec41.appspot.com',
    androidClientId: '331308178402-85rgpft3r1j3snaq8o06p6ag9imbcdr0.apps.googleusercontent.com',
    iosClientId: '331308178402-4eckq378mduijjpste4l308v520j8v7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2TVX2ik-uqoCTyL50grg-HDcVslDH8Z4',
    appId: '1:331308178402:ios:0e1d156480f47c1db737bb',
    messagingSenderId: '331308178402',
    projectId: 'manga-bec41',
    storageBucket: 'manga-bec41.appspot.com',
    androidClientId: '331308178402-85rgpft3r1j3snaq8o06p6ag9imbcdr0.apps.googleusercontent.com',
    iosClientId: '331308178402-4eckq378mduijjpste4l308v520j8v7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiRFfe-cYlyLbjwnw79ssNdirAKT51bgM',
    appId: '1:331308178402:web:0e561e59228e4eecb737bb',
    messagingSenderId: '331308178402',
    projectId: 'manga-bec41',
    authDomain: 'manga-bec41.firebaseapp.com',
    storageBucket: 'manga-bec41.appspot.com',
    measurementId: 'G-WNLTE7LZ83',
  );
}
